name: build-kernel
on:
  workflow_dispatch:
jobs:
  build-ksu:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git ccache pngcrush schedtool maven lib32ncurses5-dev xsltproc libxml2-utils squashfs-tools lzop flex build-essential bc libssl-dev libswitch-perl libxml-simple-perl zip unzip g++-multilib bison gperf zlib1g-dev automake device-tree-compiler
          sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo

      - name: Clone repo and sync
        run: |
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m oneplus12_v.xml --depth=1
          repo sync

      - name: Fix wifi issues
        run: |
          rm kernel_platform/common/android/abi_gki_protected_exports_aarch64
          rm kernel_platform/common/android/abi_gki_protected_exports_x86_64

      - name: Include KSU
        run: |
          cd kernel_platform
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Setup susfs4ksu
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu.git --depth 1 --branch gki-android14-6.1
          cp -r susfs4ksu/kernel_patches/KernelSU/* kernel_platform/KernelSU
          rm -r susfs4ksu/kernel_patches/KernelSU
          cp -r susfs4ksu/kernel_patches/* kernel_platform/common
          cd kernel_platform/KernelSU
          patch -p1 < 10_enable_susfs_for_ksu.patch
          cd ../common
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch

      - uses: actions/checkout@v4
        with:
          path: op12-kernel
          fetch-depth: 0
      - name: Include custom defconfig
        run: |
          cat op12-kernel/custom_defconfig >> \
              kernel_platform/common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig/true/g' kernel_platform/common/build.config.gki

      - name: Build kernel
        run: |
          cd kernel_platform
          mkdir out
          touch common/.scmversion
          python3 build_with_bazel.py -t pineapple gki --lto=thin --config=fast --nouse_action_cache --repository_cache="" -o "$(pwd)/out"

      # https://github.com/tiann/KernelSU/blob/69f31abd62e4f275bb33c9b478961d09231f154d/.github/workflows/gki-kernel.yml#L220
      - name: Prepare artifacts
        run: |
          mkdir output
          cp kernel_platform/out/dist/Image output
          cp kernel_platform/out/dist/Image.lz4 output
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth 1
          rm -rf AnyKernel3/.git
          cp kernel_platform/out/dist/Image AnyKernel3

      - name: Upload Image and Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: Image-op12
          path: output/*

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-op12
          path: AnyKernel3/*
