name: Build and Release Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive
  ROOT_DIR_PREFIX: "OP12-A15"
  BRANCH: "android14-6.1"
  CCACHE_DIR: /home/runner/.ccache
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "6"
  CCACHE_MAXSIZE: "5G"
  CCACHE_HARDLINK: "true"
  MAKEFLAGS: "-j$(nproc)"
  TERM: xterm-256color

jobs:
  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Setup Build Environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            python3-pip \
            curl \
            git \
            zip \
            unzip \
            gcc \
            g++ \
            make \
            ninja-build \
            file \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            wget \
            build-essential \
            python3-dev \
            python3-setuptools \
            rsync \
            ccache \
            pigz \
            parallel
          sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 5G
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Clone Repo and Sync
        run: |
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m oneplus12_v.xml --depth=1
          repo sync -j$(nproc)

      - name: Include KSU
        run: |
          cd kernel_platform/msm-kernel
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -

      - name: Setup susfs4ksu
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu.git --depth 1 --branch gki-android14-6.1
          mv susfs4ksu/kernel_patches/KernelSU susfs4ksu/kernel_patches/KernelSU-Next
          cp -r susfs4ksu/kernel_patches/* kernel_platform/msm-kernel
          cd kernel_platform/msm-kernel/KernelSU-Next
          patch -p1 < 10_enable_susfs_for_ksu.patch || true
          cd ..
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch

      - name: Fix Failed susfs4ksu Patches
        run: |
          git clone https://github.com/TheWildJames/kernel_patches.git --depth 1
          cp kernel_patches/* kernel_platform/msm-kernel
          cd kernel_platform/msm-kernel
          patch -p1 -F 3 < selinux.c_fix.patch
          patch -p1 -F 3 < apk_sign.c_fix.patch
          patch -p1 -F 3 < core_hook.c_fix.patch

      - uses: actions/checkout@v4
        with:
          path: op12-kernel
          fetch-depth: 0

      - name: Include Custom Defconfig
        run: |
          cat op12-kernel/custom_defconfig >> kernel_platform/msm-kernel/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig/true/g' kernel_platform/msm-kernel/build.config.gki

      - name: Build Kernel
        run: |
          cd kernel_platform
          mkdir out
          touch .scmversion
          python3 build_with_bazel.py -t pineapple gki -o "$(pwd)/out"
      - name: Prepare Artifacts
        run: |
          mkdir output
          cp kernel_platform/out/dist/Image output
          cp kernel_platform/out/dist/Image.lz4 output
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth 1
          rm -rf AnyKernel3/.git
          cp kernel_platform/out/dist/Image AnyKernel3

      - name: Upload Image and Image.lz4
        uses: actions/upload-artifact@v4
        with:
          name: Image-op12
          path: output/*

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-op12
          path: AnyKernel3/*

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            output/Image
            output/Image.lz4
            AnyKernel3/*
          tag_name: "v$(date +'%Y.%m.%d-%H%M%S')"
          name: "OP12 A15 android14-6.1 With KernelSU & SUSFS"
          body: |
            OnePlus 12 Kernel Release
            - Based on Android 14 (6.1)
            - Integrated KernelSU
            - SUSFS Support
            - Built with GitHub Actions
            - Build Date: $(date +'%Y-%m-%d %H:%M:%S')
          draft: false
          prerelease: false

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: kernel_platform/out/logs
